### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by lenhoo** [VergilGao/docker-avdc#23]
配置代理后：
`      - USE_PROXY=1
      - PROXY_TYPE="http"
      - PROXY_URI="192.168.2.2:7890"`
提示：
`Failed to parse: https://"192.168.2.2:7890"`

**Comment by VergilGao** [comment]
PROXY_URI=192.168.2.2:7890
双引号去掉试一下。

**Comment by lenhoo** [comment]
去掉双引号后：
`
[-]Connect Failed! Please check your Proxy or Network!,
[-]check_hostname requires server_hostname,
can only parse strings,
`

**Comment by VergilGao** [comment]
是这样，你加上双引号，然后把执行过程和所有的错误信息都贴上来。

**Comment by lenhoo** [comment]
配置
```
  avdc:
    image: vergilgao/avdc:latest
    container_name: avdc
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - FAILED_OUTPUT=c
      - SUCCESS_OUTPUT=a
      - USE_PROXY=1
      - PROXY_TYPE="http"
      - PROXY_URI="192.168.2.2:7890"
      - NAMING_RULE="number"
      - ESCAPE_FOLDERS=b
      - DEBUG=1
    volumes:
      - /volume3/test/av/x:/app/data
    restart: unless-stopped
```
错误
```[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
can only parse strings,
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[+]select javdb,
[-]Connect retry 2/3,
[-]Connect retry 1/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
can only parse strings,
[+]select airav,
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
[+]select fanza,
[-]Connect retry 1/3,
[-]Connect retry 2/3,
[-]Connect retry 3/3,
[-]Connect Failed! Please check your Proxy or Network!,
[-]Failed to parse: https://"192.168.2.2:7890",
Traceback (most recent call last):,
  File "AV_Data_Capture.py", line 188, in <module>,
    create_data_and_move(movie_path, conf, conf.debug()),
  File "AV_Data_Capture.py", line 90, in create_data_and_move,
    core_main(file_path, n_number, c),
  File "/app/core.py", line 730, in core_main,
    json_data = get_data_from_json(number, filepath, conf)  # 定义番号,
  File "/app/core.py", line 123, in get_data_from_json,
    json_data = json.loads(MT[source](func_mapping[source], (file_number,)).get()),
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get,
    raise self._value,
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker,
    result = (True, func(*args, **kwds)),
  File "/app/WebCrawler/fanza.py", line 256, in main,
    if "404 Not Found" not in htmlcode:,
TypeError: argument of type 'NoneType' is not iterable,
```

**Comment by VergilGao** [comment]
> 去掉双引号后：
> `[-]Connect Failed! Please check your Proxy or Network!, [-]check_hostname requires server_hostname, can only parse strings,`

docker-compose的话，你把双引号都去掉，然后更新一下镜像，我刚刚同步了上游的4.6.5版本，应该解决了你这里的报错问题。
